### PR TITLE
Mod Support for Origins + AE2Things

### PR DESCRIPTION
**Pull request by arichorn**
decided to put support for both of these! and if I gotten the names wrong then I am terribly sorry if they don't work

### CODE REVIEW

**Comment by arichorn** [comment]
the weird thing is origins isn't working, I don't know the original file name of the mod. I'll look and look around for it.

**Comment by arichorn** [comment]
sorry for the addition commits. I was fixing the origins issue and it's resolved now! 👍

**Comment by arichorn** [comment]
1d64e82c79333ba18719776e796fb0be

**Comment by arichorn** [comment]
Nebulr if your reading this then I am terribly sorry with the 7 commits, I screwed up 2 of the mods Origins & AE2Things and I had to fix them and make them work as intended. my fault for the extra directories.

**Comment by nebuIr** [comment]
First of all, thank you for your help! Always appreciated 👍 And no need to apologize for the additional commits, it happens 🙂

Regarding the _Origins_ mod, I made a few color adjustments, added a missing texture, and marked only **1.19** as supported since this pull request only affects branch [mc/1.19](https://github.com/nebuIr/Default-Dark-Mode/tree/mc/1.19).

As for _AE2 Things_, I checked your changes and everything looks good 👍 Only thing I noticed is the file `crystal_growth.png` should be inside of an `ae2` folder and not `ae2things`. But for the same reason as above, I removed the _AE2 Things_ files from this pull request as it currently only supports **1.18**. You can open a new pull request on the [mc/1.18](https://github.com/nebuIr/Default-Dark-Mode/tree/mc/1.18) branch and then I will go ahead and merge it.

**Comment by arichorn** [comment]
Sorry my mistake! Next time I’ll merge it in those and make sure to check the Minecraft versions

**Pull request merged**
